### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by holaymolay** [holaymolay/cartvertising.info#1]
- [x] write a better introduction paragraph
- [ ] fix responsiveness of ad-sizes cards
- [x] develop How Ads Are Offered section
- [x] do something with footer

Other points of consideration:
- it might make sense to add more details about the benefits of the program.
- look into creating an optional link that displays customized information about the appt setter or sales rep or rate card

**Comment by holaymolay** [comment]
done. 

now i'm working on a link-generator page that will allow links with parameters to be created.

e.g....   https://cartvertising.info?price=true&agentFirst=john&agentLast=smith&agentPhone=5555555555&agentEmail=jsmith@example.com
